### ISSUE TITLE
Partiality Launcher.bat fails when started from search bar (wrong directory)

### ISSUE THREAD

**Issue by aaay-aaay** [PartialityModding/PartialityLauncher#3]
(I have only tested this in Windows 10. It would be nice if some other people tested this.)
If Partiality Launcher.bat is ran from the "search bar" in Windows, it starts in C:\Windows\System32 and then fails to find bin/PartialityLauncher.Desktop.exe. That can be confusing and is also quite annoying.

To fix it, you can just add `cd %~dp0` at the top of the file, so... pls do that. :)

**Comment by DiddySPS** [comment]
I have the exact same issue, and I was wondering which file and how you would add that?

> (I have only tested this in Windows 10. It would be nice if some other people tested this.)
> If Partiality Launcher.bat is ran from the "search bar" in Windows, it starts in C:\Windows\System32 and then fails to find bin/PartialityLauncher.Desktop.exe. That can be confusing and is also quite annoying.
> 
> To fix it, you can just add `cd %~dp0` at the top of the file, so... pls do that. :)

**Comment by ZandrXandr** [comment]
1.0.0 will use a better system for launching the application, so this will be fixed then. If you want to launch partiality from searches or the task bar, use the PartialityLauncher.exe instead.
