### ISSUE TITLE
Can't install any mod

### ISSUE THREAD

**Issue by Sharaj00** [PartialityModding/PartialityLauncher#5]
problem solved

**Comment by LuLfy** [comment]
okay, i checked mod on pc of my friend, and he doesn't have these problems, but he did the same thing.
i think, i have problem from my side, incompatibility and etc.
he have win 10, i have win 8.1

**Comment by Sharaj00** [comment]
help

**Comment by Sharaj00** [comment]
now i have installed win 10, and now i have another problem
![unknown](https://user-images.githubusercontent.com/16534883/54665891-e7b2d300-4b1a-11e9-8fa7-1ce96193270b.png)
why it not working?

**Comment by Sharaj00** [comment]
i recorded a video about what i do
https://cdn.discordapp.com/attachments/431534164932689921/557622330185220098/bandicam_2019-03-20_00-48-26-115.mp4
